# Generated by Django 3.1.6 on 2021-02-07 23:53

import auctions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(models.DecimalField(decimal_places=2, default=1.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)]))]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to=auctions.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
