# Generated by Django 3.1.6 on 2021-02-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210208_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Motors', 'Motors'), ('Home & Garden', 'Home & Garden'), ('Clothing & Accessories', 'Clothing & Accessories'), ('Sports', 'Sports'), ('Health & Beauty', 'Health & Beauty'), ('Toys', 'Toys'), ('Business & Industrial', 'Business & Industrial'), ('Food & Grocery', 'Food & Grocery'), ('Others', 'Others')], default='Others', max_length=32),
        ),
    ]
